env: flex
runtime: custom
env_variables:
  ROOT_URL: https://foxyphilips.appspot-preview.com
  MONGO_URL: mongodb+srv://admin:adminpassword@cluster0-gszjc.gcp.mongodb.net/test?w=majority
  # DISABLE_WEBSOCKETS: "1"
skip_files:
- ^(.*/)?\.dockerignore$
- ^(.*/)?\npm-debug.log$
- ^(.*/)?\yarn-error.log$
- ^(.*/)?\.git$
- ^(.*/)?\.hg$
- ^(.*/)?\.svn$